type IAPIObject = {
    hydratable: string;
    data: {
        artwork_url: string;
        created_at: string;
        description: string;
        duration: number;
        embeddable_by: string;
        genre: string;
        id: number;
        kind: string;
        label_name: string;
        last_modified: string;
        license: string;
        likes_count: number;
        managed_by_feeds: boolean;
        permalink: string;
        permalink_url: string;
        public: boolean;
        purchase_title: any;
        purchase_url: any;
        release_date: any;
        reposts_count: number;
        secret_token: any;
        sharing: string;
        tag_list: string;
        title: string;
        uri: string;
        user_id: number;
        set_type: string;
        is_album: boolean;
        published_at: string;
        display_date: string;
        user: {
            avatar_url: string;
            city: any;
            comments_count: number;
            country_code: any;
            created_at: string;
            creator_subscriptions: {
                product: {
                    id: string;
                };
            }[];
            creator_subscription: {
                product: {
                    id: string;
                };
            };
            description: any;
            followers_count: number;
            followings_count: number;
            first_name: string;
            full_name: string;
            groups_count: number;
            id: number;
            kind: string;
            last_modified: string;
            last_name: string;
            likes_count: number;
            playlist_likes_count: number;
            permalink: string;
            permalink_url: string;
            playlist_count: number;
            reposts_count: any;
            track_count: number;
            uri: string;
            urn: string;
            username: string;
            verified: boolean;
            visuals: any;
            badges: {
                pro: boolean;
                pro_unlimited: boolean;
                verified: boolean;
            };
            station_urn: string;
            station_permalink: string;
        };
        tracks: ({
            artwork_url: string;
            caption: any;
            commentable: boolean;
            comment_count: number;
            created_at: string;
            description: string;
            downloadable: boolean;
            download_count: number;
            duration: number;
            full_duration: number;
            embeddable_by: string;
            genre: string;
            has_downloads_left: boolean;
            id: number;
            kind: string;
            label_name: any;
            last_modified: string;
            license: string;
            likes_count: number;
            permalink: string;
            permalink_url: string;
            playback_count: number;
            public: boolean;
            publisher_metadata: any;
            purchase_title: any;
            purchase_url: any;
            release_date: any;
            reposts_count: number;
            secret_token: any;
            sharing: string;
            state: string;
            streamable: boolean;
            tag_list: string;
            title: string;
            track_format: string;
            uri: string;
            urn: string;
            user_id: number;
            visuals: any;
            waveform_url: string;
            display_date: string;
            media: {
                transcodings: {
                    url: string;
                    preset: string;
                    duration: number;
                    snipped: boolean;
                    format: {
                        protocol: string;
                        mime_type: string;
                    };
                    quality: string;
                }[];
            };
            station_urn: string;
            station_permalink: string;
            track_authorization: string;
            monetization_model: string;
            policy: string;
            user: {
                avatar_url: string;
                first_name: string;
                followers_count: number;
                full_name: string;
                id: number;
                kind: string;
                last_modified: string;
                last_name: string;
                permalink: string;
                permalink_url: string;
                uri: string;
                urn: string;
                username: string;
                verified: boolean;
                city: string;
                country_code: string;
                badges: {
                    pro: boolean;
                    pro_unlimited: boolean;
                    verified: boolean;
                };
                station_urn: string;
                station_permalink: string;
            };
        } | {
            artwork_url: any;
            caption: any;
            commentable: boolean;
            comment_count: number;
            created_at: string;
            description: string;
            downloadable: boolean;
            download_count: number;
            duration: number;
            full_duration: number;
            embeddable_by: string;
            genre: string;
            has_downloads_left: boolean;
            id: number;
            kind: string;
            label_name: any;
            last_modified: string;
            license: string;
            likes_count: number;
            permalink: string;
            permalink_url: string;
            playback_count: number;
            public: boolean;
            publisher_metadata: {
                id: number;
                urn: string;
                contains_music: boolean;
            };
            purchase_title: any;
            purchase_url: any;
            release_date: any;
            reposts_count: number;
            secret_token: any;
            sharing: string;
            state: string;
            streamable: boolean;
            tag_list: string;
            title: string;
            track_format: string;
            uri: string;
            urn: string;
            user_id: number;
            visuals: any;
            waveform_url: string;
            display_date: string;
            media: {
                transcodings: {
                    url: string;
                    preset: string;
                    duration: number;
                    snipped: boolean;
                    format: {
                        protocol: string;
                        mime_type: string;
                    };
                    quality: string;
                }[];
            };
            station_urn: string;
            station_permalink: string;
            track_authorization: string;
            monetization_model: string;
            policy: string;
            user: {
                avatar_url: string;
                first_name: string;
                followers_count: number;
                full_name: string;
                id: number;
                kind: string;
                last_modified: string;
                last_name: string;
                permalink: string;
                permalink_url: string;
                uri: string;
                urn: string;
                username: string;
                verified: boolean;
                city: string;
                country_code: string;
                badges: {
                    pro: boolean;
                    pro_unlimited: boolean;
                    verified: boolean;
                };
                station_urn: string;
                station_permalink: string;
            };
        } | {
            artwork_url: string;
            caption: any;
            commentable: boolean;
            comment_count: number;
            created_at: string;
            description: string;
            downloadable: boolean;
            download_count: number;
            duration: number;
            full_duration: number;
            embeddable_by: string;
            genre: string;
            has_downloads_left: boolean;
            id: number;
            kind: string;
            label_name: any;
            last_modified: string;
            license: string;
            likes_count: number;
            permalink: string;
            permalink_url: string;
            playback_count: number;
            public: boolean;
            publisher_metadata: {
                id: number;
                urn: string;
                contains_music: boolean;
            };
            purchase_title: any;
            purchase_url: any;
            release_date: any;
            reposts_count: number;
            secret_token: any;
            sharing: string;
            state: string;
            streamable: boolean;
            tag_list: string;
            title: string;
            track_format: string;
            uri: string;
            urn: string;
            user_id: number;
            visuals: any;
            waveform_url: string;
            display_date: string;
            media: {
                transcodings: {
                    url: string;
                    preset: string;
                    duration: number;
                    snipped: boolean;
                    format: {
                        protocol: string;
                        mime_type: string;
                    };
                    quality: string;
                }[];
            };
            station_urn: string;
            station_permalink: string;
            track_authorization: string;
            monetization_model: string;
            policy: string;
            user: {
                avatar_url: string;
                first_name: string;
                followers_count: number;
                full_name: string;
                id: number;
                kind: string;
                last_modified: string;
                last_name: string;
                permalink: string;
                permalink_url: string;
                uri: string;
                urn: string;
                username: string;
                verified: boolean;
                city: any;
                country_code: any;
                badges: {
                    pro: boolean;
                    pro_unlimited: boolean;
                    verified: boolean;
                };
                station_urn: string;
                station_permalink: string;
            };
        } | {
            id: number;
            kind: string;
            monetization_model: string;
            policy: string;
            artwork_url?: undefined;
            caption?: undefined;
            commentable?: undefined;
            comment_count?: undefined;
            created_at?: undefined;
            description?: undefined;
            downloadable?: undefined;
            download_count?: undefined;
            duration?: undefined;
            full_duration?: undefined;
            embeddable_by?: undefined;
            genre?: undefined;
            has_downloads_left?: undefined;
            label_name?: undefined;
            last_modified?: undefined;
            license?: undefined;
            likes_count?: undefined;
            permalink?: undefined;
            permalink_url?: undefined;
            playback_count?: undefined;
            public?: undefined;
            publisher_metadata?: undefined;
            purchase_title?: undefined;
            purchase_url?: undefined;
            release_date?: undefined;
            reposts_count?: undefined;
            secret_token?: undefined;
            sharing?: undefined;
            state?: undefined;
            streamable?: undefined;
            tag_list?: undefined;
            title?: undefined;
            track_format?: undefined;
            uri?: undefined;
            urn?: undefined;
            user_id?: undefined;
            visuals?: undefined;
            waveform_url?: undefined;
            display_date?: undefined;
            media?: undefined;
            station_urn?: undefined;
            station_permalink?: undefined;
            track_authorization?: undefined;
            user?: undefined;
        })[];
        track_count: number;
        url: string;
    };
};


type IApiTrack = IAPIObject['data']['tracks'][0];
type ITrackExtend = {
    updated_artwork?: string;
    started?: boolean;
};

export type ICustomTrack = IApiTrack & ITrackExtend;

export type IAPI = IAPIObject & {
    data: {
        updated_artwork?: string;
    };
};


// npx tsc --declaration arquivo.ts